import type { NextPage } from 'next'
import Head from 'next/head'

const breakPoint = 'max-width: 1024px';

const Home: NextPage = () => {
  return (
    <>
      <div className="container">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="main">
          <h1 className="title">
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>
        </main>
      </div>

      <style jsx>
        {`
          .container {
            padding: 0 2rem;
          }

          .main {
            min-height: 100vh;
            padding: 4rem 0;
            flex: 1;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
          }
  
          .title {
            margin: 0;
            line-height: 1.15;
            font-size: 4rem;
            text-align: center;
          }
          
          @media (${breakPoint}) {
            .title {
              color: red;
            }
          }
        `}
      </style>
    </>
  )
}

export default Home
